### ISSUE TITLE
CSV file is read incorrectly

### ISSUE THREAD

**Issue by landisrm** [gregorbj/VisionEval#238] opened 2019-02-11 16:27 UTC
While running VERPAT multiple scenarios, I had a problem with reading in one of the scenario inputs file.  All of the scenarios using this file failed.  [L2_Bad_bzone_pop_emp_prop.csv.txt](https://github.com/gregorbj/VisionEval/files/2851971/L2_Bad_bzone_pop_emp_prop.csv.txt).  I traced the failure to the fact that this file was read in improperly and did not have all of the header columns.  This file was exported from Excel on Windows.  

I was able to get the scenarios to run with a copy created from the L1 scenario input CSV file, which I opened in LibreOffice and simply changed the values.   
[L2_Good_bzone_pop_emp_prop.csv.txt](https://github.com/gregorbj/VisionEval/files/2851970/L2_Good_bzone_pop_emp_prop.csv.txt)

I believe the files are read in by visioneval::processModuleInputs in validation.R and can be debugged there.

**Comment by gregorbj** [comment] 2019-02-11 17:35
Thanks for adding this issue. I've also noticed the need to catch errors in input file headers. The function should check that all columns have headers and that the names of all the headers correspond to the names in the specifications. It needs to return helpful error messages.

**Comment by gregorbj** [comment] 2019-02-20 22:03
This is now addressed in the ve_rspm_state branch. The function now loads the input csv file in a 'try' function and the result is checked to determine success or failure. If failure a message identifying the file is wrong is output
      Data_df <- try(read.csv(file.path(Dir, File), as.is = TRUE), silent = TRUE)
      if (class(Data_df) == "try-error") {
        Msg <-
          paste0(
            "Input file error. File '", File, "' required by '",
            ModuleName, "' is not properly formatted. Could be caused by rows ",
            "not having same number of entries or values not properly comma ",
            "separated."
          )
        FileErr_ <- c(FileErr_, Msg)
        FileErr_ls <- c(FileErr_ls, FileErr_)
        next()
      }

**Comment by landisrm** [comment] 2019-02-26 17:46
I did finally discover what the problem with the CSV file was.  It had been saved as a UTF-8 CSV in Excel.  It turns out that Excel adds a "Byte Order Mark" to the beginning of UTF-8 CSVs which gets interpreted as a character when read into R, at least on Windows.  I have code that strips out the BOM if it is present.  I will add it in.

**Closed** 2019-03-03 16:45 UTC
